### PR TITLE
use Aurelia logging

### PR DESCRIPTION
**Pull request by Thanood**
solves this
> todo: switch with aurelia native dev log

😃 

btw: I've included the sample bundles just because they are registered with git.

### CODE REVIEW

**Comment by vegarringdal** [comment]
Great, that looked a lot better when I tested it
We might need to look at how much info it print out, it kinda prints a lot
But its useful during development :-)

**Comment by Thanood** [comment]
Yeah, it's more of a `trace` log.
I'd keep it until a stable release.

**Comment by vegarringdal** [comment]
We could maybe add a option to just show the error also for now

**Comment by Thanood** [comment]
You can do that with Aurelia's logging settings.
Just remove `.developmentLogging()` and provoke an error. 😃 

Or set the log level explicitly for fuse logger.

**Comment by vegarringdal** [comment]
ok, never tried that, maybe we should add that as a comment readme file later

**Pull request merged**
